name: movie_app
description: A high-performance Flutter movie app using TMDb API
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio_cache_interceptor_hive_store: ^4.0.0
  dio_retry_plus: ^2.0.7
  # State Management
  flutter_bloc: ^8.1.3
  # Network and API
  dio: ^5.3.2
  json_annotation: ^4.8.1
  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  # UI Components
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  # Utils
  equatable: ^2.0.5
  get_it: ^7.6.0
  injectable: ^2.3.0
  logger: ^2.5.0
  dartz: ^0.10.1
  flutter_staggered_animations: ^1.1.1
  font_awesome_flutter: ^10.8.0
  ad_gridview: ^0.0.5
  connectivity_plus: ^6.1.1
  retry: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  hive_generator: ^2.0.1
  injectable_generator: ^2.4.0
